#-------------------------------------------------
#
# Project created by QtCreator 2012-04-03T17:48:33
#
# THIS IS NOT A REAL PRO FILE
# this need to change at some point to be properly included
# I AM SHOUTING
#
#-------------------------------------------------

SOURCES += \
    ../json-cpp/src/lib_json/json_writer.cpp \
    ../json-cpp/src/lib_json/json_value.cpp \
    ../json-cpp/src/lib_json/json_reader.cpp

HEADERS += \
    ../json-cpp/src/lib_json/json_tool.h \
    ../json-cpp/src/lib_json/json_batchallocator.h \
    ../json-cpp/include/json/writer.h \
    ../json-cpp/include/json/value.h \
    ../json-cpp/include/json/reader.h \
    ../json-cpp/include/json/json.h \
    ../json-cpp/include/json/forwards.h \
    ../json-cpp/include/json/features.h \
    ../json-cpp/include/json/config.h \
    ../json-cpp/include/json/autolink.h

INCLUDEPATH += ../json-cpp/include
